---
- name: Setup Minecraft Server
  hosts: minecraft
  become: yes

  tasks:

    - name: Download Amazon Corretto 21 RPM
      get_url:
        url: https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.rpm
        dest: /tmp/amazon-corretto-21-x64-linux-jdk.rpm

    - name: Install Amazon Corretto 21
      yum:
        name: /tmp/amazon-corretto-21-x64-linux-jdk.rpm
        state: present

    - name: Set JAVA_HOME in /etc/profile.d/java.sh
      copy:
        dest: /etc/profile.d/java.sh
        content: |
          export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
          export PATH=$JAVA_HOME/bin:$PATH
        owner: root
        group: root
        mode: '0644'

    - name: Source JAVA_HOME for current session
      shell: source /etc/profile.d/java.sh
      args:
        executable: /bin/bash


    - name: Create minecraft directory
      file:
        path: /home/ec2-user/minecraft
        state: directory
        owner: ec2-user
        group: ec2-user
    
    - name: Remove old minecraft server jar
      file: 
        path: /home/ec2-user/minecraft/server.jar
        state: absent


    - name: Download Minecraft server jar
      get_url:
        url: https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar
        dest: /home/ec2-user/minecraft/server.jar
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Accept Minecraft EULA
      copy:
        dest: /home/ec2-user/minecraft/eula.txt
        content: "eula=true\n"
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Set default java to Corretto 21 for all users
      alternatives:
        name: java
        path: /usr/lib/jvm/java-21-amazon-corretto/bin/java


    - name: Create systemd service for Minecraft
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/home/ec2-user/minecraft
          ExecStart=/usr/bin/java -Xmx1024M -Xms1024M -jar server.jar nogui
          Restart=always

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Check what java is in path for systemd
      command: readlink -f /usr/bin/java
      register: java_path_output

    - name: Print system java path
      debug:
        var: java_path_output.stdout


    - name: Enable and restart Minecraft service
      systemd:
        name: minecraft
        enabled: yes
        state: restarted

